apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oh-team5-poi
  name: oh-team5-poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oh-team5-poi
  strategy: {}
  template:
    metadata:
      labels:
        app: oh-team5-poi
    spec:
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/poi:1.0
        name: poi
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: server
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: password
        resources: {}
status: {}
