apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oh-team5-java
  name: oh-team5-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oh-team5-java
  strategy: {}
  template:
    metadata:
      labels:
        app: oh-team5-java
    spec:
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/user-java:1.0
        name: user-java
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: server
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: password
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oh-team5-java
  name: user-java-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: oh-team5-java
  type: NodePort
status:
  loadBalancer: {}