apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  labels:
    app: oh-team5-trips
  name: oh-team5-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oh-team5-trips
  strategy: {}
  template:
    metadata:
      labels:
        app: oh-team5-trips
    spec:
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/trips:1.0
        name: trips
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: server
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: password
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  labels:
    app: oh-team5-trips
  name: trips-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: oh-team5-trips
  type: NodePort
status:
  loadBalancer: {}