apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tripviewer
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  strategy: {}
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/tripviewer:1.0
        name: tripviewer
        env:
        - name: USERPROFILE_API_ENDPOINT
          value:  http://userprofile-svc.api.svc.cluster.local:8000
        - name: TRIPS_API_ENDPOINT
          value:  http://trips-svc.api.svc.cluster.local:8000
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tripview-service
  namespace: web
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: tripviewer