apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  labels:
    app: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  strategy: {}
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ot5keyvault"
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/userprofile:1.0
        name: userprofile
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  labels:
    app: userprofile
  name: userprofile-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
  type: NodePort
status:
  loadBalancer: {}
