apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  strategy: {}
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - image: registryrbq9427.azurecr.io/tripinsights/userprofile:1.0
        name: userprofile
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: server
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecrets
              key: password
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: userprofile
  name: userprofile-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
  type: NodePort
status:
  loadBalancer: {}
